"""Add dependencies and summary to Repository

Revision ID: 1016bfe3f3d8
Revises: 2e9c2f053072
Create Date: 2026-06-24 22:15:23.817680

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '1016bfe3f3d8'
down_revision: Union[str, None] = '2e9c2f053072'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('repositories', sa.Column('dependencies', postgresql.JSON(astext_type=sa.Text()), nullable=True))
    op.add_column('repositories', sa.Column('summary', sa.Text(), nullable=True))
    op.add_column('repositories', sa.Column('architecture_diagram', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('repositories', 'architecture_diagram')
    op.drop_column('repositories', 'summary')
    op.drop_column('repositories', 'dependencies')
    # ### end Alembic commands ###
