"""add trial_sessions table

Revision ID: 578ac6ee1342
Revises: 1016bfe3f3d8
Create Date: 2026-07-08 11:29:31.283884

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '578ac6ee1342'
down_revision: Union[str, None] = '1016bfe3f3d8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('trial_sessions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('session_token', sa.String(length=64), nullable=False),
    sa.Column('repos_analyzed', sa.Integer(), nullable=True),
    sa.Column('chat_messages_used', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('last_used_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_trial_sessions_session_token'), 'trial_sessions', ['session_token'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_trial_sessions_session_token'), table_name='trial_sessions')
    op.drop_table('trial_sessions')
    # ### end Alembic commands ###
