"""initial_schema

Revision ID: bec56d532463
Revises: 
Create Date: 2026-06-23 15:38:43.442676

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'bec56d532463'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('repositories',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('github_url', sa.String(length=500), nullable=False),
    sa.Column('branch', sa.String(length=100), nullable=False),
    sa.Column('commit_hash', sa.String(length=40), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('primary_language', sa.String(length=50), nullable=True),
    sa.Column('total_files', sa.Integer(), nullable=True),
    sa.Column('total_lines', sa.Integer(), nullable=True),
    sa.Column('language_stats', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('github_url')
    )
    op.create_index(op.f('ix_repositories_name'), 'repositories', ['name'], unique=False)
    op.create_index(op.f('ix_repositories_status'), 'repositories', ['status'], unique=False)
    op.create_table('analysis_jobs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('repo_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('current_step', sa.String(length=50), nullable=True),
    sa.Column('progress_percentage', sa.Integer(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('files_scanned', sa.Integer(), nullable=True),
    sa.Column('files_ignored', sa.Integer(), nullable=True),
    sa.Column('secrets_skipped', sa.Integer(), nullable=True),
    sa.Column('languages_detected', sa.Integer(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['repo_id'], ['repositories.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_analysis_jobs_repo_id'), 'analysis_jobs', ['repo_id'], unique=False)
    op.create_index(op.f('ix_analysis_jobs_status'), 'analysis_jobs', ['status'], unique=False)
    op.create_table('files',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('repo_id', sa.UUID(), nullable=False),
    sa.Column('path', sa.String(length=1000), nullable=False),
    sa.Column('language', sa.String(length=50), nullable=True),
    sa.Column('size_bytes', sa.Integer(), nullable=True),
    sa.Column('line_count', sa.Integer(), nullable=True),
    sa.Column('is_indexed', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['repo_id'], ['repositories.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_files_language'), 'files', ['language'], unique=False)
    op.create_index(op.f('ix_files_repo_id'), 'files', ['repo_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_files_repo_id'), table_name='files')
    op.drop_index(op.f('ix_files_language'), table_name='files')
    op.drop_table('files')
    op.drop_index(op.f('ix_analysis_jobs_status'), table_name='analysis_jobs')
    op.drop_index(op.f('ix_analysis_jobs_repo_id'), table_name='analysis_jobs')
    op.drop_table('analysis_jobs')
    op.drop_index(op.f('ix_repositories_status'), table_name='repositories')
    op.drop_index(op.f('ix_repositories_name'), table_name='repositories')
    op.drop_table('repositories')
    # ### end Alembic commands ###
